{"name": "test_labmbdatest_radio_button_demo_value", "status": "failed", "statusDetails": {"message": "AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following 2 failures were found in \"test_labmbdatest_radio_button_demo_value\" (DemoPytest.test_assertion_soft.AsserttionsTst):\n+----------------------+----------------------+----------------------+\n Failure 1 (\"Verify Gender, Title & Age Group\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"C:\\Users\\atipj\\Documents\\Portfolio\\Lambdatest\\Selenium_Python_101\\DemoPytest\\test_assertion_soft.py\", line 27, in test_labmbdatest_radio_button_demo_value\n    self.soft_assert(self.assertIs,\n  File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\softest\\case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 1166, in assertIs\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 715, in fail\n    raise self.failureException(msg)\nAssertionError: 'Male' is not 'Male' : Gender Is NOT Correct!\n\n-+ [1/2] +-\n\n+----------------------+----------------------+----------------------+\n Failure 2 (\"Verify Gender, Title & Age Group\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"C:\\Users\\atipj\\Documents\\Portfolio\\Lambdatest\\Selenium_Python_101\\DemoPytest\\test_assertion_soft.py\", line 31, in test_labmbdatest_radio_button_demo_value\n    self.soft_assert(self.assertIn,\n  File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\softest\\case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 1152, in assertIn\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 715, in fail\n    raise self.failureException(msg)\nAssertionError: '51' not found in '15 - 50' : Age Group Is NOT Correct\n\n-+ [2/2] +-", "trace": "self = <DemoPytest.test_assertion_soft.AsserttionsTst testMethod=test_labmbdatest_radio_button_demo_value>\n\n    def test_labmbdatest_radio_button_demo_value(self):\n        driver = webdriver.Chrome()\n        driver.maximize_window()\n        driver.get(\"https://www.lambdatest.com/selenium-playground/radiobutton-demo\")\n        driver.find_element(By.XPATH,\n            \"//h4[contains(text(),'Gender')]\"\n            \"//following::input[@value='Male']\").click()\n        driver.find_element(By.XPATH,\n            \"//h4[contains(text(),'Age')]\"\n            \"//following::input[@value='15 - 50']\").click()\n        driver.find_element(By.XPATH,\n            \"//button[text()='Get values']\").click()\n        gender = driver.find_element(By.CSS_SELECTOR,\n            \".genderbutton\").text\n        age_group = driver.find_element(By.CSS_SELECTOR,\n            \".groupradiobutton\").text\n        print(\"Gender Object: \\t\", id(gender))\n        print(\"Male Object: \\t\", id(\"Male\"))\n        self.soft_assert(self.assertIs,\n        \"Male\", gender, \"Gender Is NOT Correct!\")\n        self.soft_assert(self.assertTrue,\n        driver.title.__contains__(\"Selenium Grid Online\"))\n        self.soft_assert(self.assertIn,\n        \"51\", age_group, \"Age Group Is NOT Correct\")\n>       self.assert_all(\"Verify Gender, Title & Age Group\")\n\nDemoPytest\\test_assertion_soft.py:33: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\softest\\case.py:139: in assert_all\n    self.fail(''.join(failure_output))\nE   AssertionError: ++++ soft assert failure details follow below ++++\nE   \nE   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nE   The following 2 failures were found in \"test_labmbdatest_radio_button_demo_value\" (DemoPytest.test_assertion_soft.AsserttionsTst):\nE   +----------------------+----------------------+----------------------+\nE    Failure 1 (\"Verify Gender, Title & Age Group\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"C:\\Users\\atipj\\Documents\\Portfolio\\Lambdatest\\Selenium_Python_101\\DemoPytest\\test_assertion_soft.py\", line 27, in test_labmbdatest_radio_button_demo_value\nE       self.soft_assert(self.assertIs,\nE     File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\softest\\case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 1166, in assertIs\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: 'Male' is not 'Male' : Gender Is NOT Correct!\nE   \nE   -+ [1/2] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 2 (\"Verify Gender, Title & Age Group\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"C:\\Users\\atipj\\Documents\\Portfolio\\Lambdatest\\Selenium_Python_101\\DemoPytest\\test_assertion_soft.py\", line 31, in test_labmbdatest_radio_button_demo_value\nE       self.soft_assert(self.assertIn,\nE     File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\softest\\case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 1152, in assertIn\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\unittest\\case.py\", line 715, in fail\nE       raise self.failureException(msg)\nE   AssertionError: '51' not found in '15 - 50' : Age Group Is NOT Correct\nE   \nE   -+ [2/2] +-"}, "attachments": [{"name": "stdout", "source": "e7b38c5c-d22b-45fd-aff1-41cf1518d556-attachment.txt", "type": "text/plain"}], "start": 1710443308748, "stop": 1710443310765, "uuid": "db004da3-7b0b-4380-b812-56fecb1ac987", "historyId": "fa029f6dac786234adb8eaaf163d9992", "testCaseId": "fa029f6dac786234adb8eaaf163d9992", "fullName": "DemoPytest.test_assertion_soft.AsserttionsTst#test_labmbdatest_radio_button_demo_value", "labels": [{"name": "parentSuite", "value": "DemoPytest"}, {"name": "suite", "value": "test_assertion_soft"}, {"name": "subSuite", "value": "AsserttionsTst"}, {"name": "host", "value": "LAPTOP-U9R56RQR"}, {"name": "thread", "value": "26916-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "DemoPytest.test_assertion_soft"}]}