{"uuid": "ebe1ba61-0b44-4955-9e9c-b8b6f77525b0", "children": ["8803a39f-21cd-428d-b6ce-c532a5e8a01a"], "befores": [{"name": "driver_initialization", "status": "broken", "statusDetails": {"message": "TypeError: WebDriver.__init__() got an unexpected keyword argument 'desired_capabilities'\n", "trace": "  File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\atipj\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\atipj\\Documents\\Portfolio\\Lambdatest\\Selenium_Python_101\\conftest.py\", line 64, in driver_initialization\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n"}, "start": 1710443314989, "stop": 1710443314989}], "start": 1710443314989, "stop": 1710443323236}